Further optimize the performance
sisl/AA228FinalProject pull request #10
Opened 2021-05-07 06:17 UTC by Wu-Chenyang

Changes include:
- remove packages irrelevant to the domain (How about renaming this package to be something like `Roomba.jl`?)
- make the state type of the discrete roomba to be `Int`, such that it can be solved by `SARSOP.jl` (SARSOP involves an operation to check if two states are the same. However, the equivalence of `RoombaState` depends on the specific discretization.)
- rewrite the collision detection code to make it faster

2021-05-08 03:18 UTC, mykelk requested changes

2021-05-08 03:18 UTC, mykelk commented on Project.toml
> +ProfileView = "c46f51b8-102a-5cf2-8d2c-8597cb0e0da7"
Why is ProfileView added here?

2021-05-08 03:19 UTC, mykelk commented
Thanks for the PR! I'm hoping @kunalmenda can do a quick review and then we can merge.

2021-05-08 06:00 UTC, Wu-Chenyang commented on Project.toml
> +ProfileView = "c46f51b8-102a-5cf2-8d2c-8597cb0e0da7"
It was added for debugging. I will remove it.

2021-05-08 06:16 UTC, zsunberg commented
This is very cool, Thanks! I might be able to do a review tomorrow. I think a rename of the package would be in order. If you submit a PR to rename the module RoombaPOMDPs.jl, I will accept it and remove the package (I think Roomba might be too generic of a name - that sounds like it could be an interface for controlling a roomba).

2021-05-08 13:03 UTC, mykelk commented
Yes, good idea to rename to RoombaPOMDPs.jl.

2021-05-08 18:23 UTC, zsunberg approved these changes
I did not closely look at everything, but overall I think it looks good after you fix Mykel's suggestion.

2021-05-08 18:23 UTC, zsunberg commented on test/runtests.jl
> +@testset "DiscreteRoomba Test" begin
Would POMDPTesting.has_consistent_distributions work here?

2021-05-09 11:30 UTC, Wu-Chenyang commented on test/runtests.jl
> +@testset "DiscreteRoomba Test" begin
It does work.

2021-05-09 12:08 UTC, Wu-Chenyang commented
I have made changes according to the suggestions mentioned. :)

2021-05-09 19:01 UTC, mykelk approved these changes

2021-05-09 19:02 UTC, merged

2021-05-09 19:05 UTC, mykelk commented
Thanks! Would you mind addressing #11 ?

2021-05-12 14:41 UTC, Wu-Chenyang commented
I will address it in the next several days.

2021-05-12 14:46 UTC, mykelk commented
Thanks so much!

2021-05-14 00:30 UTC, zsunberg commented
Thanks a bunch! This is great!